import type { App } from 'vue';
import MCurtain from './MCurtain/index.vue';
import MList from './MList/index.vue';
import MDiv from './MDiv/index.vue';
import MScale from './MScale/index.vue';
import MTextellips from './MTextellips/index.vue';
import MIfShow from './MIfShow/index.vue';
import MValidator from './MValidator/index.vue';
export declare const components: Record<string, any>;
export declare const MoonUI: {
    install(app: App): App<any>;
};
export { MCurtain };
export { MList };
export { MDiv };
export { MScale };
export { MTextellips };
export { MIfShow };
export { MValidator };
export default MoonUI;
